---
title: "linear_model"
author: "Xinyin Miao"
date: "2025-11-06"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
```

```{r}
data("nyc_airbnb")
```

look at the data/ do some cleaning

```{r}
nyc_airbnb = 
  nyc_airbnb |> 
  mutate(stars = review_scores_location / 2) |> 
  rename(
    borough = neighbourhood_group,
    neighborhood = neighbourhood) |> 
  filter(borough != "Staten Island") |> 
  select(price, stars, borough, neighborhood, room_type)
```

do regression

```{r}
fit = lm(price ~ stars + borough, data = nyc_airbnb)
```

do some additional cleaning then refit

```{r}
nyc_airbnb = 
  nyc_airbnb |> 
  mutate(
    borough = fct_infreq(borough),
    room_type = fct_infreq(room_type))

fit = lm(price ~ stars + borough, data = nyc_airbnb)
```

Look at `lm` stuff

```{r, eval = FALSE}
summary(fit)
names(summary(fit))
summary(fit)[["coefficients"]]
summary(fit)[["df"]]

fitted.values(fit)
```

Look at cleaner `lm` stuff

```{r}
fit |> 
  broom::tidy() |> 
  mutate(
    term = str_replace(term, "borough", "Borough: ")
  ) |> 
  select(term, estimate, p.value) |> 
  knitr::kable(digits = 3)

fit |> 
  broom::glance()
```





